server:
  port: 9999

logging:
  level:
    org.springframework: DEBUG

# sql
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/mp?characterEncoding=utf-8&&serverTime=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatisPlus
# 开启下划线和驼峰的映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
